<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### Your Name

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```

```{r}
with(planets, Dotplot(gaia_dist, bin=FALSE))
```

```{r}
with(planets, Dotplot(gaia_gmag, bin=FALSE))
```

```{r}
with(planets, Dotplot(pl_angsep, bin=FALSE))
```

```{r}
with(planets, Dotplot(gaia_dist, bin=FALSE))
```

```{r}
with(planets, Hist(gaia_gmag, scale="frequency", breaks="Sturges", col="darkgray"))
```

```{r}
with(planets, Hist(pl_angsep, scale="frequency", breaks="Sturges", col="darkgray"))
```

```{r}
test <- with(planets, Hist(pl_angsep, scale="frequency", breaks="Sturges", 
  col="darkgray"))
```


